### ISSUE TITLE
Contribute to the official DefinitelyTyped repo

### ISSUE THREAD

**Issue by Justin-Credible** [danibo86/ionic-typescript-definitions#1]
Great work on this TS definition, been waiting for this for a while.

I think it would be great if you contributed to the official DefinitelyTyped repo, and I'm sure a lot of other people would find it beneficial too!

https://github.com/borisyankov/DefinitelyTyped

**Comment by danibo86** [comment]
I just submitted a pull request (https://github.com/borisyankov/DefinitelyTyped/pull/3407)

Checkout also the new version with various fixes, and promises based on angular.d.ts!

**Comment by cbeams** [comment]
@danibo86, any plans to fix the build breakages on borisyankov/DefinitelyTyped#3407? Thanks for putting this together.
