### ISSUE TITLE
Can we post this to borisyankov/DefinitelyTyped?

### ISSUE THREAD

**Issue by tangentlin** [danibo86/ionic-typescript-definitions#3]
I am trying to use tsd to manage the definitions, and I wonder if this can become part of the borisyankov/DefinitelyTyped repo, thanks!

**Comment by danibo86** [comment]
Of course this can become part of the borisyankov/DefinitelyTyped repo!
I just submitted a pull request (https://github.com/borisyankov/DefinitelyTyped/pull/3407)

Checkout also the new version with various fixed and promises based on angular.d.ts!
